server:
  port: 8080

spring:
  profiles:
    active: dev
  redis:
    host: 47.100.229.195
    port: 26379
    password: spdb1234
    timeout: 60
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8


###################  mybatis-plus配置  ###################
mybatis-plus:
  mapper-locations: classpath*:mapping/*.xml
  typeAliasesPackage: com.sm.blog.model
  global-config:
    id-type: 0  #0:数据库ID自增   1:用户输入id  2:全局唯一id(IdWorker)  3:全局唯一ID(uuid)
    db-column-underline: true
    refresh-mapper: true
    logic-delete-value: 0
    logic-not-delete-value: 1
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
  configuration:
    map-underscore-to-camel-case: false
    cache-enabled: true #配置的缓存的全局开关
    lazyLoadingEnabled: true #延时加载的开关
    multipleResultSetsEnabled: true #开启的话，延时加载一个属性时会加载该对象全部属性，否则按需加载属性


logging:
  level.root: info
  path: logs/

---
##########################################################
###################  开发环境的profile  ###################
##########################################################

spring:
  profiles: dev
  devtools:
      restart:
        enabled: true #热部署开关
  datasource:
    url: jdbc:mysql://www.strawman.xin:3306/myblog?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: manage
    password: spdb1234
    db-name: myblog
    filters: log4j,wall,mergeStat
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql语句,调试用
---
##########################################################
###################  线上环境的profile  ###################
##########################################################

spring:
  profiles: pro
  devtools:
      restart:
        enabled: false #热部署开关
  datasource:
    url: jdbc:mysql://localhost:3306/myblog?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: manage
    password: spdb1234
    db-name: myblog
    filters: log4j,wall,mergeStat
logging:
    file: blog.log

---

#  mvc:
#    favicon:
#      enabled: false



###################  guns配置  ###################
blog:
  whiteIp: ["127.0.0.1","0:0:0:0:0:0:0:1"]
  allowedErrorReqNum: 6
  swagger-open: true #是否开启swagger (true/false)
  kaptcha-open: false #是否开启登录时验证码 (true/false)
  #file-upload-path: d:/tmp  #文件上传目录(不配置的话为java.io.tmpdir目录)
  muti-datasource-open: false #是否开启多数据源(true/false)
  spring-session-open: false #是否开启spring session,如果是多机环境需要开启(true/false)
  session-invalidate-time: 1800 #session失效时间(只在单机环境下生效，多机环境在SpringSessionConfig类中配置) 单位：秒
  session-validation-interval: 900 #多久检测一次失效的session(只在单机环境下生效) 单位：秒












